permalink: /:basename
url: https://blog.mathsoftware.engineer

title: Math Software Engineer
author: Tobias Briones

image: /favicon.png

social-network-links:
  email: "contact@mathsoftware.engineer"
  github: tobiasbriones
  twitter: tobiasbriones_
  reddit: tobiasbriones
  linkedin: tobiasbriones
  stackoverflow: "9560258/tobiasbriones"
  instagram: tobiasbriones
  
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

post_search: true

twitter:
  card: summary_large_image

exclude:
  - Main.kt
